/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * OMDb API
 * This API requires authorization, you can get a free key here: [http://omdbapi.com/apikey.aspx](http://omdbapi.com/apikey.aspx)
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse,
  AxiosError
} from 'axios'
import {
  useQuery
} from '@tanstack/react-query'
import type {
  UseQueryOptions,
  QueryFunction,
  UseQueryResult,
  QueryKey
} from '@tanstack/react-query'
import type {
  GetIdParams
} from '../models'



/**
 * @summary Returns a single result based on the ID provided
 */
export const getId = (
    params: GetIdParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.get(
      `/?i`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetIdQueryKey = (params: GetIdParams,) => [`/?i`, ...(params ? [params]: [])] as const;
  

    
export const getGetIdQueryOptions = <TData = Awaited<ReturnType<typeof getId>>, TError = AxiosError<unknown>>(params: GetIdParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getId>>, TError, TData>, axios?: AxiosRequestConfig}
): UseQueryOptions<Awaited<ReturnType<typeof getId>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIdQueryKey(params);

  
  
    const queryFn: QueryFunction<Awaited<ReturnType<typeof getId>>> = ({ signal }) => getId(params, { signal, ...axiosOptions });
    
      
      
   return  { queryKey, queryFn, ...queryOptions}}

export type GetIdQueryResult = NonNullable<Awaited<ReturnType<typeof getId>>>
export type GetIdQueryError = AxiosError<unknown>

/**
 * @summary Returns a single result based on the ID provided
 */
export const useGetId = <TData = Awaited<ReturnType<typeof getId>>, TError = AxiosError<unknown>>(
 params: GetIdParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getId>>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetIdQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

