/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * OMDb API
 * This API requires authorization, you can get a free key here: [http://omdbapi.com/apikey.aspx](http://omdbapi.com/apikey.aspx)
 * OpenAPI spec version: 1.0
 */
import type { GetTitleType } from './getTitleType';
import type { GetTitlePlot } from './getTitlePlot';
import type { GetTitleR } from './getTitleR';

export type GetTitleParams = {
/**
 * Title of movie or series
 */
t: string;
/**
 * Year of release
 */
y?: number;
/**
 * Return movie or series
 */
type?: GetTitleType;
/**
 * Return short or full plot
 */
plot?: GetTitlePlot;
/**
 * The response type to return
 */
r?: GetTitleR;
/**
 * JSONP callback name
 */
callback?: string;
};
