/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * OMDb API
 * This API requires authorization, you can get a free key here: [http://omdbapi.com/apikey.aspx](http://omdbapi.com/apikey.aspx)
 * OpenAPI spec version: 1.0
 */

export * from './getIdParams';
export * from './getIdPlot';
export * from './getIdR';
export * from './getTitleParams';
export * from './getTitlePlot';
export * from './getTitleR';
export * from './getTitleType';
export * from './titleSearchParams';
export * from './titleSearchR';
export * from './titleSearchType';