/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * OMDb API
 * This API requires authorization, you can get a free key here: [http://omdbapi.com/apikey.aspx](http://omdbapi.com/apikey.aspx)
 * OpenAPI spec version: 1.0
 */

export type TitleSearchR = typeof TitleSearchR[keyof typeof TitleSearchR];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TitleSearchR = {
  json: 'json',
  xml: 'xml',
} as const;
